---
filter_secrets: false
os: linux
dist: xenial
addons:
  apt:
    packages:
      - inkscape
      - texlive-latex-base
      - dvipng
      - plantuml
language: python
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
install:
  - pip install --upgrade setuptools
  - pip install --upgrade pip
  - pip install pytest pre-commit
  - pip install -c requirements.txt -c test_requirements.txt -e .[tests,sphinx,svgsupport,aafiguresupport,mathsupport,rawhtmlsupport]
env:
  - TEST_CMD="pytest"
script:
  - $TEST_CMD
matrix:
  include:
    - name: "lint"
      python: 3.6
      env:
        - TEST_CMD="pre-commit run --all-files"
    - name: "3.5"
      python: 3.5
    - name: "3.6"
      python: 3.6
    - name: "3.7"
      python: 3.7
    - name: "3.8"
      python: 3.8
